//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.API.Models.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Product_Property
    {
        public long PropertyID { get; set; }
        public long ProductID { get; set; }
        public string Roles { get; set; }
        public string Key { get; set; }
        public string StringValue { get; set; }
        public Nullable<double> DoubleValue { get; set; }
        public Nullable<int> IntValue { get; set; }
    
        public virtual CRM_Products CRM_Products { get; set; }
    }
}
