//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.API.Models.CRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HCRMEntities : DbContext
    {
        public HCRMEntities()
            : base("name=HCRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CRM_Customer> CRM_Customer { get; set; }
        public virtual DbSet<CRM_Customer_Address> CRM_Customer_Address { get; set; }
        public virtual DbSet<CRM_Menu> CRM_Menu { get; set; }
        public virtual DbSet<CRM_Product_Details_Template> CRM_Product_Details_Template { get; set; }
        public virtual DbSet<CRM_Products> CRM_Products { get; set; }
        public virtual DbSet<CRM_Provider> CRM_Provider { get; set; }
        public virtual DbSet<CRM_Provider_Address> CRM_Provider_Address { get; set; }
        public virtual DbSet<CRM_Receipt_Delivery> CRM_Receipt_Delivery { get; set; }
        public virtual DbSet<CRM_Receipt_Details> CRM_Receipt_Details { get; set; }
        public virtual DbSet<CRM_Receipt_Return> CRM_Receipt_Return { get; set; }
        public virtual DbSet<CRM_Receipt_Warehouse> CRM_Receipt_Warehouse { get; set; }
        public virtual DbSet<CRM_Role_Menu> CRM_Role_Menu { get; set; }
        public virtual DbSet<CRM_Tags> CRM_Tags { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CRM_Product_Property> CRM_Product_Property { get; set; }
    }
}
