//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_Page
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cms_Page()
        {
            this.Cms_PageImage = new HashSet<Cms_PageImage>();
            this.Cms_PageContent = new HashSet<Cms_PageContent>();
        }
    
        public int PageID { get; set; }
        public Nullable<int> PageLevel { get; set; }
        public Nullable<int> PageParentID { get; set; }
        public string PageParentIDSets { get; set; }
        public string Position { get; set; }
        public string Icon { get; set; }
        public string Template { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> Views { get; set; }
        public string CssClass { get; set; }
        public Nullable<bool> IsPublish { get; set; }
        public string PropertyCategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cms_PageImage> Cms_PageImage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cms_PageContent> Cms_PageContent { get; set; }
    }
}
