//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_NotificationContent
    {
        public int NotificationContentID { get; set; }
        public Nullable<int> NotificationID { get; set; }
        public string LanguageID { get; set; }
        public string EmailSubject { get; set; }
        public string EmailFrom { get; set; }
        public string EmailTos { get; set; }
        public string EmailCCs { get; set; }
        public string EmailBCCs { get; set; }
        public string EmailBody { get; set; }
        public string FromName { get; set; }
    
        public virtual Cms_Notification Cms_Notification { get; set; }
    }
}
