//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cms_Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cms_Article()
        {
            this.Cms_ArticleContent = new HashSet<Cms_ArticleContent>();
            this.Cms_ArticleImage = new HashSet<Cms_ArticleImage>();
        }
    
        public int ArticleID { get; set; }
        public Nullable<int> PageID { get; set; }
        public string Position { get; set; }
        public string Image { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> Views { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public string Workplace { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cms_ArticleContent> Cms_ArticleContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cms_ArticleImage> Cms_ArticleImage { get; set; }
    }
}
