//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HCMSEntities : DbContext
    {
        public HCMSEntities()
            : base("name=HCMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cms_AdminMenu> Cms_AdminMenu { get; set; }
        public virtual DbSet<Cms_Article> Cms_Article { get; set; }
        public virtual DbSet<Cms_ArticleContent> Cms_ArticleContent { get; set; }
        public virtual DbSet<Cms_ArticleImage> Cms_ArticleImage { get; set; }
        public virtual DbSet<Cms_Banner> Cms_Banner { get; set; }
        public virtual DbSet<Cms_Contact> Cms_Contact { get; set; }
        public virtual DbSet<Cms_Newsletter> Cms_Newsletter { get; set; }
        public virtual DbSet<Cms_Notification> Cms_Notification { get; set; }
        public virtual DbSet<Cms_NotificationContent> Cms_NotificationContent { get; set; }
        public virtual DbSet<Cms_Page> Cms_Page { get; set; }
        public virtual DbSet<Cms_PageContent> Cms_PageContent { get; set; }
        public virtual DbSet<Cms_PageImage> Cms_PageImage { get; set; }
    }
}
