//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Role_Menu
    {
        public string Role { get; set; }
        public int MenuID { get; set; }
    
        public virtual CRM_Menu CRM_Menu { get; set; }
    }
}
