//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HCMS.CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRM_Receipt_Details
    {
        public long OrderDetailId { get; set; }
        public long OrderId { get; set; }
        public long ProductId { get; set; }
        public int Quantity { get; set; }
        public double UnitPrice { get; set; }
        public Nullable<int> Album_producId { get; set; }
    
        public virtual CRM_Products CRM_Products { get; set; }
        public virtual CRM_Receipt_Delivery CRM_Receipt_Delivery { get; set; }
    }
}
